from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train and score full-US real estate demand model")
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("../data/real_estate_training_data_full.csv"),
        help="Input training CSV generated by export_real_estate_training_data.py",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("../data/scored_real_estate_demand_full.csv"),
        help="Output scored CSV for backend/frontend heatmap",
    )
    parser.add_argument("--test-size", type=float, default=0.25, help="Train/test split fraction")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    input_path = args.input.resolve()
    output_path = args.output.resolve()

    if not input_path.exists():
        raise FileNotFoundError(f"Missing input CSV: {input_path}")

    output_path.parent.mkdir(parents=True, exist_ok=True)

    df = pd.read_csv(input_path)
    required_cols = [
        "owner_households",
        "renter_households",
        "owner_share_pct",
        "renter_share_pct",
        "owner_yoy_pct",
        "renter_yoy_pct",
        "housing_units_yoy_pct",
        "median_rent_usd",
        "demand_index",
    ]
    missing = [column for column in required_cols if column not in df.columns]
    if missing:
        raise ValueError(f"Input CSV missing required columns: {missing}")

    work = df.copy()
    work["target_demand_pressure"] = work["demand_index"] * (1.0 + work["renter_share_pct"] / 100.0)

    feature_cols = [
        "owner_households",
        "renter_households",
        "owner_share_pct",
        "renter_share_pct",
        "owner_yoy_pct",
        "renter_yoy_pct",
        "housing_units_yoy_pct",
        "median_rent_usd",
    ]

    x = work[feature_cols].fillna(0.0)
    y = work["target_demand_pressure"].fillna(0.0)

    x_train, x_test, y_train, y_test = train_test_split(
        x,
        y,
        test_size=max(0.05, min(args.test_size, 0.5)),
        random_state=42,
    )

    model = RandomForestRegressor(
        n_estimators=500,
        random_state=42,
        min_samples_leaf=2,
        n_jobs=-1,
    )
    model.fit(x_train, y_train)

    pred = model.predict(x_test)
    mae = mean_absolute_error(y_test, pred)
    r2 = r2_score(y_test, pred)

    work["predicted_pressure"] = model.predict(x)
    work["predicted_risk"] = "OK"
    work.loc[work["predicted_pressure"] >= 125, "predicted_risk"] = "STOCKOUT_RISK"
    work.loc[work["predicted_pressure"] <= 92, "predicted_risk"] = "OVERSTOCK_RISK"
    watch_mask = (work["predicted_pressure"] >= 108) & (work["predicted_pressure"] < 125)
    work.loc[watch_mask, "predicted_risk"] = "WATCH"

    output_columns = [
        "id",
        "hub",
        "zcta",
        "state",
        "latitude",
        "longitude",
        "predicted_pressure",
        "predicted_risk",
        "owner_households",
        "renter_households",
        "owner_yoy_pct",
        "renter_yoy_pct",
        "housing_units_yoy_pct",
        "median_rent_usd",
    ]
    available_columns = [column for column in output_columns if column in work.columns]
    scored = work[available_columns].sort_values("predicted_pressure", ascending=False)
    scored.to_csv(output_path, index=False)

    print(f"Trained rows: {len(work)}")
    print(f"MAE: {mae:.3f}")
    print(f"R2: {r2:.3f}")
    print(f"Saved scored CSV: {output_path}")


if __name__ == "__main__":
    main()
